services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
        - ./mqtt-broker/config:/mosquitto/config

  temperature-sensor:
    build: ./temperature-sensor
    volumes:
      - ./temperature-sensor:/app
    depends_on:
      - mqtt-broker

  light-sensor:
    build: ./light-sensor
    volumes:
      - ./light-sensor:/app
    depends_on:
      - mqtt-broker

  actuator-fan:
    build: ./actuator-fan
    volumes:
      - ./actuator-fan:/app
    depends_on:
      - mqtt-broker

  lamp-actuator:
    build: ./lamp-actuator
    volumes:
      - ./lamp-actuator:/app
    depends_on:
      - mqtt-broker

  fastapi-app:
    build: ./fastapi-app
    ports:
        - "8000:8000"
    volumes:
     - ./fastapi-app/app:/app/app
    depends_on:
      - mqtt-broker
